services:
     ifensl_nav_bar.generator.json:
        class: Ifensl\Bundle\NavBarBundle\Generator\JsonMenuGenerator
        arguments: [%ifensl_nav_bar.menu%]

     ifensl_nav_bar.generator.html:
        class: Ifensl\Bundle\NavBarBundle\Generator\HtmlMenuGenerator
        arguments: [%ifensl_nav_bar.menu%, @templating]

     ifensl_nav_bar.generator.css:
        class: Ifensl\Bundle\NavBarBundle\Generator\CssMenuGenerator
        arguments: [%ifensl_nav_bar.menu%, @templating]
